package io.swisschain.domain.exceptions;

public class AlreadyExistsException extends Exception {
  public AlreadyExistsException(Throwable cause) {
    super(cause);
  }
}
